---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Init docker for juice shop and serve presentation
    init: docker pull bkimminich/juice-shop
    command: |
      docker run --rm -p 3000:3000 bkimminich/juice-shop
      python -m http.server 8080 --directory "$GITPOD_REPO_ROOT"/prez

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: ignore
    visibility: private
    name: juice-shop
    
  - port: 8080
    onOpen: ignore
    visibility: private
    name: presentation

vscode:
  extensions:
    - wayou.vscode-todo-highlight
    - manuth.eslint-language-service
    - dbaeumer.vscode-eslint
    - DavidAnson.vscode-markdownlint
    - EditorConfig.EditorConfig
